name: Build

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      - name: Install Haxelib
        run: |
          haxelib setup C:\haxelib
          haxelib install hxcpp
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install hscript-iris
          haxelib install tjson
          haxelib install hxDiscordRpc
          haxelib install flxanimate
          haxelib install linc_luajit
          haxelib install hxvlc
          haxelib run lime setup
        shell: cmd
        
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
        
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}" -D officialBuild
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
